# Generated by Django 4.0.3 on 2022-03-05 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_alter_usercar_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
