# Generated by Django 4.0.3 on 2022-03-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_carmodel_user_alter_carbrand_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_models', to='cars.carbrand'),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
        ),
    ]
